-- ============================================
-- Supabase Schema for Auth & Leaderboard System
-- Execute this SQL in Supabase SQL Editor
-- ============================================

-- 1. PROFILES: Linked to Supabase Auth
-- Stores user profile information (display name)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text default 'Unknown Pilot',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. GAME_RESULTS: History of all plays
-- Stores every game result for score tracking
create table public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  score integer not null,
  played_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. TRIGGER: Auto-create profile on signup
-- Automatically creates a profile when a new user registers
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, 'Unknown Pilot');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. VIEW: Leaderboard (High Score Aggregation)
-- Aggregates each user's highest score for ranking
create view public.leaderboard_view as
  select
    profiles.username,
    max(game_results.score) as high_score
  from game_results
  join profiles on game_results.user_id = profiles.id
  group by profiles.id, profiles.username
  order by high_score desc;

-- 5. SECURITY: Row Level Security (RLS)
-- Enable RLS on both tables
alter table public.profiles enable row level security;
alter table public.game_results enable row level security;

-- Public Read Access
-- Anyone can view profiles and scores
create policy "Public profiles are viewable by everyone."
  on profiles for select using (true);

create policy "Public scores are viewable by everyone."
  on game_results for select using (true);

-- Owner Write Access
-- Users can only update their own profile
create policy "Users can update own profile."
  on profiles for update using (auth.uid() = id);

-- Users can only insert their own scores
create policy "Users can insert own score."
  on game_results for insert with check (auth.uid() = user_id);

-- ============================================
-- IMPORTANT: Enable Anonymous Sign-in
-- ============================================
-- Go to Supabase Dashboard > Authentication > Settings
-- Under "Auth Providers", enable "Anonymous Sign-ins"
-- ============================================
